In [1]:
import numpy as np

Array Notation

In [7]:
# All the Row and Column Matrices are consider as one dimention arrays

one_D_array = np.array([1,2,3])     # One Dimensional Array
print(one_D_array)

two_D_array = np.array([(1,2,3),(4,5,6)])     # Two Dimensional Array
print(two_D_array)

three_D_array = np.array([(1,2,3),(4,5,6),(7,8,6)])     # Three Dimensional Array ..... and So on .....
print(three_D_array)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 6]]
